[package]
name = "veloce-unix"
description = "An ETSI Geonetworking V2X stack for unix systems"
repository = "https://github.com/kurkpitaine/veloce"
version = "0.1.0"
license = "GPL-3.0-only OR LicenseRef-Veloce-Software-1.0"
authors = ["Veloce developers <veloce@ferroxyde.com>"]
categories = ["network-programming", "embedded"]
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
libc = "0.2"
log = { version = "0.4", features = ["std"] }
macaddr = "1.0"
mio = { version = "1.0", features = ["os-ext", "os-poll", "net"] }
rand = "0.9"
secrecy = { version = "0.10", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
veloce = { path = "../veloce" }
veloce-gnss = { path = "../veloce-gnss" }
veloce-ipc = { path = "../veloce-ipc" }
veloce-nxp-phy = { path = "../veloce-nxp-phy", default-features = false }

[features]
nxp-phy-r17 = ["veloce-nxp-phy/llc-r17_1"]
nxp-phy-r16 = ["veloce-nxp-phy/llc-r16"]

default = ["nxp-phy-r17"]

[[bin]]
name = "veloce"
path = "src/veloce.rs"
