[package]
name = "veloce-nxp-phy"
version = "0.1.0"
authors = ["Thibaud Rouillé <thibaud.rouille@gmail.com>"]
edition = "2021"
description = "Veloce NXP SAF5x00 PHY"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.3"
veloce = { path = "../veloce" }

[dev-dependencies]
clap = { version = "4.4.11", features = ["derive"] }
log = { version = "0.4.20", default-features = false }
uom = { version = "0.34.0", features = ["autoconvert", "f32"] }
veloce-asn1 = { path = "../veloce-asn1" }
rasn = "0.12.4"

[build-dependencies]
bindgen = "0.69.2"

[[example]]
name = "usb_device"

[[example]]
name = "llc_device"
